server:
  port: 8089

spring:
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  datasource:
    url: jdbc:h2:./db/movie_review;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  h2:
    console:
      enabled: false
  freemarker:
    expose-session-attributes: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        generate_statistics: true
        format_sql: true
    show-sql: true
  #=========== Mail config
  mail:
    host: smtp.gmail.com
    username: gwinbleid86@gmail.com
    password: YOUR_PASSWORD
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  messages:
#    encoding: ISO-8859-1


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
      hibernate:
        #        stat: debug
        type: trace
    sql: trace
    web: debug
  #
  #  pattern:
  #    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/spring.log

