
name: Java CI with Maven

on:
  # push:
    # branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]
    workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{ github.actor }}/movie_review_image:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
        
    - name: Start Maven Test & Package
      run: mvn clean package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: movie_review.jar
        path: ./target/Movie_review*.jar
        retention-days: 1

  publish:
    needs: build
    name: Publish image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: movie_review.jar

      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Publish
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMG_NAME }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMG_NAME }}

  deploy:
    needs: publish
    name: Deploy Image

    runs-on: ubuntu-latest

    steps:
      - name: Connect & Pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            cd ${{ secrets.WORK_DIR }}
            docker compose pull
            docker compose up -d
            exit